[versions]
androidGradlePlugin = "8.12.0"
kotlin = "2.0.21"
appcompat = "1.7.0"
appiconloader = "1.5.0"
biometricKtx = "1.2.0-alpha05"
commonsText = "1.12.0"
composeBom = "2024.11.00"
composePreference = "1.1.1"
constraintlayout = "2.1.4"
coreKtx = "1.13.1"
dhizukuApi = "2.5.3"
hiddenapibypass = "4.3"
insetter = "0.6.1"
kotlinxCoroutinesAndroid = "1.9.0"
lifecycleLivedataKtx = "2.8.5"
material = "1.12.0"
navigationKtx = "2.8.0"
pinyin4j = "2.5.1"
preferenceKtx = "1.2.1"
shizuku = "13.1.5"
swiperefreshlayout = "1.1.0"
workRuntimeKtx = "2.9.1"
xposed = "82"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometricKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationKtx" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
appiconloader = { module = "me.zhanghai.android.appiconloader:appiconloader", version.ref = "appiconloader" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
compose-preference = { module = "me.zhanghai.compose.preference:library", version.ref = "composePreference" }
dhizuku-api = { module = "io.github.iamr0s:Dhizuku-API", version.ref = "dhizukuApi" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
pinyin4j = { module = "com.belerweb:pinyin4j", version.ref = "pinyin4j" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
